archive "..\..\..\archives\.compiled\sound.dz"
basedir "..\..\..\..\..\..\..\..\..\AppData\Local\Temp\_Vectorier\archives\sound"
file "beep.wav" 0 dz
file "birds1.wav" 0 dz
file "birds2.wav" 0 dz
file "birds3.wav" 0 dz
file "bodyfall1.wav" 0 dz
file "bodyfall2.wav" 0 dz
file "body_wall_edge.wav" 0 dz
file "bonus_pickup.wav" 0 dz
file "cash_register.wav" 0 dz
file "coil.wav" 0 dz
file "crack_body.wav" 0 dz
file "crack_bones.wav" 0 dz
file "cs_technopar_footslide.wav" 0 dz
file "cs_tehnopark_crash.wav" 0 dz
file "cs_tehnopark_wind.wav" 0 dz
file "door_close.wav" 0 dz
file "drop_chair1.wav" 0 dz
file "enemy_charge.wav" 0 dz
file "enemy_discharge.wav" 0 dz
file "flying_body.wav" 0 dz
file "glass_break.wav" 0 dz
file "glass_item_drop1.wav" 0 dz
file "glass_item_drop2.wav" 0 dz
file "glass_item_drop3.wav" 0 dz
file "hands1.wav" 0 dz
file "hands2.wav" 0 dz
file "hands_edge.wav" 0 dz
file "hit_body.wav" 0 dz
file "hit_chair1.wav" 0 dz
file "hit_head.wav" 0 dz
file "hit_legs.wav" 0 dz
file "landing_foot.wav" 0 dz
file "landing_hard.wav" 0 dz
file "landing_light.wav" 0 dz
file "landing_light1.wav" 0 dz
file "landing_light2.wav" 0 dz
file "landing_light3.wav" 0 dz
file "lift.wav" 0 dz
file "lift_cover.wav" 0 dz
file "lift_cover_impact1.wav" 0 dz
file "lift_cover_impact2.wav" 0 dz
file "lift_cover_impact4.wav" 0 dz
file "m_breath_calm.wav" 0 dz
file "m_hit1.wav" 0 dz
file "m_hit2.wav" 0 dz
file "m_jump1.wav" 0 dz
file "m_jump2.wav" 0 dz
file "m_jump3.wav" 0 dz
file "m_jump4.wav" 0 dz
file "papers1.wav" 0 dz
file "papers2.wav" 0 dz
file "roll1.wav" 0 dz
file "roll2.wav" 0 dz
file "roll3.wav" 0 dz
file "rotation1.wav" 0 dz
file "rotation2.wav" 0 dz
file "shoot.wav" 0 dz
file "slide_long.wav" 0 dz
file "slide_short.wav" 0 dz
file "slide_slope.wav" 0 dz
file "step1.wav" 0 dz
file "step2.wav" 0 dz
file "step3.wav" 0 dz
file "step4.wav" 0 dz
file "sweep1.wav" 0 dz
file "sweep2.wav" 0 dz
file "sweep3.wav" 0 dz
file "sweep4.wav" 0 dz
file "trick_activate.wav" 0 dz
file "truckDTcs02.wav" 0 dz
file "ui_button_big_release.wav" 0 dz
file "ui_button_big_toggle.wav" 0 dz
file "ui_button_round_toggle.wav" 0 dz
file "ui_button_square_toggle.wav" 0 dz
file "ui_click.wav" 0 dz
file "ui_window_options.wav" 0 dz
file "ui_window_profile.wav" 0 dz
file "ui_window_shop.wav" 0 dz
file "wall_feet.wav" 0 dz
file "wall_feet_slide.wav" 0 dz
file "_cs/k0505/birds_pre1.wav" 0 dz
file "_cs/k0505/birds_pre2.wav" 0 dz
file "_cs/k0505/birds_pre3.wav" 0 dz
file "_cs/k0505/btn_click1.wav" 0 dz
file "_cs/k0505/btn_unclick1.wav" 0 dz
file "_cs/k0505/cat_growl1.wav" 0 dz
file "_cs/k0505/cat_hiss1.wav" 0 dz
file "_cs/k0505/cat_hiss2.wav" 0 dz
file "_cs/k0505/cat_hiss3.wav" 0 dz
file "_cs/k0505/cat_meow1.wav" 0 dz
file "_cs/k0505/cat_meow2.wav" 0 dz
file "_cs/k0505/cat_meow3.wav" 0 dz
file "_cs/k0505/cat_meow_s1.wav" 0 dz
file "_cs/k0505/cat_meow_s2.wav" 0 dz
file "_cs/k0505/click_machine1.wav" 0 dz
file "_cs/k0505/door_break1.wav" 0 dz
file "_cs/k0505/door_slam1.wav" 0 dz
file "_cs/k0505/door_slam2.wav" 0 dz
file "_cs/k0505/electric1.wav" 0 dz
file "_cs/k0505/elevator_creak1.wav" 0 dz
file "_cs/k0505/elevator_door_move1.wav" 0 dz
file "_cs/k0505/elevator_door_move2.wav" 0 dz
file "_cs/k0505/elevator_door_slam1.wav" 0 dz
file "_cs/k0505/elevator_door_slam2.wav" 0 dz
file "_cs/k0505/elevator_door_slam3.wav" 0 dz
file "_cs/k0505/fall_water1.wav" 0 dz
file "_cs/k0505/helicopter_landing1.wav" 0 dz
file "_cs/k0505/helicopter_loop1.wav" 0 dz
file "_cs/k0505/lift2.wav" 0 dz
file "_cs/k0505/lift_bell1.wav" 0 dz
file "_cs/k0505/light_buzz1.wav" 0 dz
file "_cs/k0505/light_buzz2.wav" 0 dz
file "_cs/k0505/metal/arrive1.wav" 0 dz
file "_cs/k0505/metal/arrive2.wav" 0 dz
file "_cs/k0505/metal/arrive3.wav" 0 dz
file "_cs/k0505/metal/hit_hard1.wav" 0 dz
file "_cs/k0505/metal/hit_hard2.wav" 0 dz
file "_cs/k0505/metal/hit_hard3.wav" 0 dz
file "_cs/k0505/metal/hit_hard4.wav" 0 dz
file "_cs/k0505/metal/hit_soft1.wav" 0 dz
file "_cs/k0505/metal/hit_soft2.wav" 0 dz
file "_cs/k0505/metal/move1.wav" 0 dz
file "_cs/k0505/metal/move2.wav" 0 dz
file "_cs/k0505/metal/move3.wav" 0 dz
file "_cs/k0505/sirens1.wav" 0 dz
file "_cs/k0505/train_horn1.wav" 0 dz
file "_cs/k0505/train_pass.wav" 0 dz
file "_cs/k0505/woosh1.wav" 0 dz
file "_cs/k0505/woosh2.wav" 0 dz