archive "..\..\..\archives\.compiled\level_xml.dz"
basedir "..\..\..\archives\uncompiled\level_xml"
file "0.xml" 0 copy
file "1.xml" 0 copy
file "2.xml" 0 copy
file "3.xml" 0 copy
file "4.xml" 0 copy
file "barrel_tower.xml" 0 copy
file "barrier_3.xml" 0 copy
file "bike.xml" 0 copy
file "buildings.xml" 0 copy
file "buildings_construction.xml" 0 copy
file "buildings_downtown.xml" 0 copy
file "buildings_lab.xml" 0 copy
file "buildings_techpark.xml" 0 copy
file "buildings_techpark_bonus.xml" 0 copy
file "cap.xml" 0 copy
file "cap_2.xml" 0 copy
file "CONSTRUCTION_BONUS_01.xml" 0 copy
file "CONSTRUCTION_BONUS_02.xml" 0 copy
file "CONSTRUCTION_BONUS_03.xml" 0 copy
file "CONSTRUCTION_BONUS_04.xml" 0 copy
file "CONSTRUCTION_BONUS_05.xml" 0 copy
file "CONSTRUCTION_BONUS_06.xml" 0 copy
file "CONSTRUCTION_BONUS_07.xml" 0 copy
file "CONSTRUCTION_BONUS_08.xml" 0 copy
file "CONSTRUCTION_BONUS_09.xml" 0 copy
file "CONSTRUCTION_HUNTER_01.xml" 0 copy
file "CONSTRUCTION_STORY_01.xml" 0 copy
file "CONSTRUCTION_STORY_02.xml" 0 copy
file "CONSTRUCTION_STORY_03.xml" 0 copy
file "CONSTRUCTION_STORY_04.xml" 0 copy
file "CONSTRUCTION_STORY_05.xml" 0 copy
file "CONSTRUCTION_STORY_06.xml" 0 copy
file "CONSTRUCTION_STORY_07.xml" 0 copy
file "CONSTRUCTION_STORY_08.xml" 0 copy
file "CONSTRUCTION_STORY_09.xml" 0 copy
file "CONSTRUCTION_STORY_10.xml" 0 copy
file "CONSTRUCTION_STORY_11.xml" 0 copy
file "cs01a_downtown_coil.xml" 0 copy
file "cs01_downtown_second.xml" 0 copy
file "cs02_downtown_flash_memory.xml" 0 copy
file "cs02_flash_memory.xml" 0 copy
file "cs02_truck2.xml" 0 copy
file "cs_bike_starting_bike.xml" 0 copy
file "cs_bike_starting_bike_and_player.xml" 0 copy
file "cs_techpark_cs01_girl.xml" 0 copy
file "cs_techpark_cs01_glider.xml" 0 copy
file "cs_techpark_cs01_glidergirl.xml" 0 copy
file "cs_techpark_cs01_main_glider.xml" 0 copy
file "cs_techpark_cs01_main_glider_girl.xml" 0 copy
file "CS_yard_cs02_glider.xml" 0 copy
file "CS_yard_cs02_lift.xml" 0 copy
file "CS_yard_cs02_lift_new.xml" 0 copy
file "CS_yard_cs02_rope.xml" 0 copy
file "door_3.xml" 0 copy
file "DOWNTOWN_BONUS_01.xml" 0 copy
file "DOWNTOWN_BONUS_02.xml" 0 copy
file "DOWNTOWN_BONUS_03.xml" 0 copy
file "DOWNTOWN_BONUS_04.xml" 0 copy
file "DOWNTOWN_BONUS_05.xml" 0 copy
file "DOWNTOWN_BONUS_06.xml" 0 copy
file "DOWNTOWN_BONUS_07.xml" 0 copy
file "DOWNTOWN_BONUS_08.xml" 0 copy
file "DOWNTOWN_BONUS_09.xml" 0 copy
file "DOWNTOWN_HUNTERMOD_01.xml" 0 copy
file "DOWNTOWN_STORY_01.xml" 0 copy
file "DOWNTOWN_STORY_02.xml" 0 copy
file "DOWNTOWN_STORY_03.xml" 0 copy
file "DOWNTOWN_STORY_04.xml" 0 copy
file "DOWNTOWN_STORY_05.xml" 0 copy
file "DOWNTOWN_STORY_06.xml" 0 copy
file "DOWNTOWN_STORY_07.xml" 0 copy
file "DOWNTOWN_STORY_08.xml" 0 copy
file "DOWNTOWN_STORY_09.xml" 0 copy
file "DOWNTOWN_STORY_10.xml" 0 copy
file "DOWNTOWN_STORY_11.xml" 0 copy
file "GEAR_CAP.xml" 0 copy
file "GEAR_SCARF.xml" 0 copy
file "GEAR_SHORTS.xml" 0 copy
file "helper.xml" 0 copy
file "hunter.xml" 0 copy
file "ladder_4.xml" 0 copy
file "ladder_8.xml" 0 copy
file "objects.xml" 0 copy
file "objects_construction.xml" 0 copy
file "objects_custom.xml" 0 copy
file "objects_downtown.xml" 0 copy
file "objects_lab.xml" 0 copy
file "objects_techpark.xml" 0 copy
file "revolution_girl.xml" 0 copy
file "shirt.xml" 0 copy
file "stool_3.xml" 0 copy
file "tail.xml" 0 copy
file "TECHPARK_BONUS_01.xml" 0 copy
file "TECHPARK_BONUS_02.xml" 0 copy
file "TECHPARK_BONUS_03.xml" 0 copy
file "TECHPARK_BONUS_04.xml" 0 copy
file "TECHPARK_BONUS_05.xml" 0 copy
file "TECHPARK_BONUS_06.xml" 0 copy
file "TECHPARK_BONUS_07.xml" 0 copy
file "TECHPARK_BONUS_08.xml" 0 copy
file "TECHPARK_BONUS_09.xml" 0 copy
file "TECHPARK_HUNTER_01.xml" 0 copy
file "TECHPARK_STORY_01.xml" 0 copy
file "TECHPARK_STORY_02.xml" 0 copy
file "TECHPARK_STORY_03.xml" 0 copy
file "TECHPARK_STORY_04.xml" 0 copy
file "TECHPARK_STORY_05.xml" 0 copy
file "TECHPARK_STORY_06.xml" 0 copy
file "TECHPARK_STORY_07.xml" 0 copy
file "TECHPARK_STORY_08.xml" 0 copy
file "TECHPARK_STORY_09.xml" 0 copy
file "TECHPARK_STORY_10.xml" 0 copy
file "TECHPARK_STORY_11.xml" 0 copy
file "TriggerTemplates.xml" 0 copy
file "_cs/FlipThoseTitle/hunter.xml" 0 copy
file "_cs/FlipThoseTitle/v2armors/BlackArmorSet.xml" 0 copy